apiVersion: v1
kind: Service
metadata:
  name: expense-tracker-service
  labels:
    app: expense-tracker-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30007
  selector:
    app: expense-tracker-service

